## ノック1: データ読み込み

In [1]:
import pandas as pd
m_store = pd.read_csv('./m_store.csv')
m_store

     store_id store_name area_cd
0           1        昭島店      TK
1           2      あきる野店      TK
2           3        足立店      TK
3           4       北千住店      TK
4           5        綾瀬店      TK
..        ...        ...     ...
192       193        桐生店      GU
193       194        高崎店      GU
194       195        館林店      GU
195       196        前橋店      GU
196       999       保守担当      TK

[197 rows x 3 columns]

In [2]:
m_area = pd.read_csv('./m_area.csv')
m_area

  area_cd wide_area narrow_area
0      TK        東京          東京
1      KN       神奈川         神奈川
2      CH        千葉          千葉
3      SA        埼玉          埼玉
4      IB       北関東          茨城
5      TO       北関東          栃木
6      GU       北関東          群馬

In [3]:
tbl_order_4 = pd.read_csv('./tbl_order_202004.csv')
tbl_order_5 = pd.read_csv('./tbl_order_202005.csv')
tbl_order_6 = pd.read_csv('./tbl_order_202006.csv')
tbl_order_4

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2
...,...,...,...,...,...,...,...,...,...,...
233255,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2
233256,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2
233257,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2
233258,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2
233259,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2

## ノック2: データ結合

In [4]:
# 4月と5月の注文データの結合
order_all = pd.concat([tbl_order_4, tbl_order_5], ignore_index=True)
order_all

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2
...,...,...,...,...,...,...,...,...,...,...
474394,47039360,154,C39765066,90,27121351,2020-05-31 21:58:58,2020-05-31 22:42:58,1,2363,1
474395,61054188,94,C19465010,41,61513298,2020-05-31 21:58:58,2020-05-31 22:40:58,0,2112,2
474396,45288914,11,C23883838,40,65359139,2020-05-31 21:58:58,2020-05-31 22:38:58,0,3838,2
474397,41608372,149,C48350551,43,42138977,2020-05-31 21:58:58,2020-05-31 22:52:58,0,1899,2
474398,40316733,169,C49087342,61,59737067,2020-05-31 21:58:58,2020-05-31 22:08:58,0,3901,2

In [5]:
# 結合後の件数の確認
len(order_all) == len(tbl_order_4) + len(tbl_order_5)

True

## ノック3: フォルダ内ファイルの一覧化

In [6]:
# カレントディレクトリの表示
import os
current_dir = os.getcwd() # カレントディレクトリを取得
current_dir

'c:\\Users\\nao23\\Documents\\Python_Projects\\02_MLSys_100Knocks\\book\\本章\\1章'

In [7]:
# カレントディレクトリの内容を一覧表示
os.listdir(current_dir)

['.gitignore',
 '100knocks_2_ML_1-10.ipynb',
 '1章_分析に向けた準備を行う10本ノック.ipynb',
 '1章_分析に向けた準備を行う10本ノック_answer.ipynb',
 'm_area.csv',
 'm_store.csv',
 'output_data',
 'tbl_order_202004.csv',
 'tbl_order_202005.csv',
 'tbl_order_202006.csv']

In [8]:
# カレントディレクトリの検索キーを設定
tbl_order_file = os.path.join(current_dir, 'tbl_order_*.csv') #カレントディレクトリと注文データファイル名を連結
tbl_order_file

'c:\\Users\\nao23\\Documents\\Python_Projects\\02_MLSys_100Knocks\\book\\本章\\1章\\tbl_order_*.csv'

In [9]:
# カレントディレクトリの注文データを一覧表示
import glob
tbl_order_files = glob.glob(tbl_order_file) # データを検索
tbl_order_files

['c:\\Users\\nao23\\Documents\\Python_Projects\\02_MLSys_100Knocks\\book\\本章\\1章\\tbl_order_202004.csv',
 'c:\\Users\\nao23\\Documents\\Python_Projects\\02_MLSys_100Knocks\\book\\本章\\1章\\tbl_order_202005.csv',
 'c:\\Users\\nao23\\Documents\\Python_Projects\\02_MLSys_100Knocks\\book\\本章\\1章\\tbl_order_202006.csv']

## ノック4: 複数データの結合

In [10]:
# 注文データファイルの一覧を基に、繰り返し処理を実行（まずはテスト用に一部のみ）
order_all = pd.DataFrame()

file = tbl_order_files[0]
order_data = pd.read_csv(file)
print(f'{file}:{len(order_data)}')

order_all = pd.concat([order_all, order_data], ignore_index=True)
order_all

c:\Users\nao23\Documents\Python_Projects\02_MLSys_100Knocks\book\本章\1章\tbl_order_202004.csv:233260

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2
...,...,...,...,...,...,...,...,...,...,...
233255,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2
233256,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2
233257,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2
233258,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2
233259,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2

In [11]:
# 繰り返し処理に書き換え
order_all = pd.DataFrame()

for file in tbl_order_files:
  file = tbl_order_files[0]
  order_data = pd.read_csv(file)
  print(f'{file}:{len(order_data)}')

  order_all = pd.concat([order_all, order_data], ignore_index=True)

c:\Users\nao23\Documents\Python_Projects\02_MLSys_100Knocks\book\本章\1章\tbl_order_202004.csv:233260
c:\Users\nao23\Documents\Python_Projects\02_MLSys_100Knocks\book\本章\1章\tbl_order_202004.csv:233260
c:\Users\nao23\Documents\Python_Projects\02_MLSys_100Knocks\book\本章\1章\tbl_order_202004.csv:233260

In [12]:
# 結合結果の確認
order_all

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2
...,...,...,...,...,...,...,...,...,...,...
699775,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2
699776,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2
699777,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2
699778,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2
699779,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2

## ノック5: データの統計量の確認

In [13]:
# 結合データの欠損値の確認
order_all.isnull().sum()

order_id             0
store_id             0
customer_id          0
coupon_cd            0
sales_detail_id      0
order_accept_date    0
delivered_date       0
takeout_flag         0
total_amount         0
status               0
dtype: int64

In [14]:
# 結合データの統計量の確認
order_all.describe()

,order_id,store_id,coupon_cd,sales_detail_id,takeout_flag,total_amount,status
count,6.997800e+05,699780.000000,699780.000000,6.997800e+05,699780.000000,699780.000000,699780.000000
mean,5.009612e+07,103.935788,49.492172,5.005261e+07,0.259976,2960.244302,3.080545
std,2.887448e+07,86.324388,28.868395,2.883530e+07,0.438621,954.518623,2.834699
min,7.000000e+01,1.000000,0.000000,4.600000e+01,0.000000,698.000000,1.000000
25%,2.514388e+07,51.000000,24.000000,2.513950e+07,0.000000,2308.000000,2.000000
50%,5.013903e+07,99.000000,49.000000,5.012261e+07,0.000000,2808.000000,2.000000
75%,7.518149e+07,148.000000,74.000000,7.497667e+07,1.000000,3617.000000,2.000000
max,9.999980e+07,999.000000,99.000000,9.999965e+07,1.000000,5100.000000,9.000000

In [15]:
# 見たいデータだけを出力
order_all['total_amount'].describe()

count    699780.000000
mean       2960.244302
std         954.518623
min         698.000000
25%        2308.000000
50%        2808.000000
75%        3617.000000
max        5100.000000
Name: total_amount, dtype: float64

In [16]:
# データ期間の確認
print(order_all['order_accept_date'].min())
print(order_all['order_accept_date'].max())
print(order_all['delivered_date'].min())
print(order_all['delivered_date'].max())

2020-04-01 11:00:00
2020-04-30 21:58:58
2020-04-01 11:10:00
2020-04-30 23:09:57

## ノック6: 不要データの削除

In [17]:
# 保守担当用のデータを除外する
order_data = order_all.loc[order_all['store_id'] != 999] #今回は store_id=999 が保守担当用のデータとなっている
order_data

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2
...,...,...,...,...,...,...,...,...,...,...
699775,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2
699776,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2
699777,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2
699778,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2
699779,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2

In [18]:
# 結合データの統計量の再確認
order_data.describe()

,order_id,store_id,coupon_cd,sales_detail_id,takeout_flag,total_amount,status
count,6.960090e+05,696009.000000,696009.000000,6.960090e+05,696009.000000,696009.000000,696009.000000
mean,5.010023e+07,99.086301,49.500890,5.005709e+07,0.259893,2959.555881,3.080111
std,2.887621e+07,55.929847,28.867062,2.883418e+07,0.438576,954.517103,2.834296
min,7.000000e+01,1.000000,0.000000,4.600000e+01,0.000000,698.000000,1.000000
25%,2.513269e+07,51.000000,24.000000,2.514448e+07,0.000000,2308.000000,2.000000
50%,5.015266e+07,99.000000,49.000000,5.013679e+07,0.000000,2808.000000,2.000000
75%,7.518520e+07,147.000000,74.000000,7.497599e+07,1.000000,3586.000000,2.000000
max,9.999980e+07,196.000000,99.000000,9.999965e+07,1.000000,5100.000000,9.000000

## ノック7: マスタデータの結合

In [19]:
# 店舗マスタを結合する
order_data = pd.merge(order_data, m_store, on='store_id', how='left')
order_data

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1,浅草店,TK
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2,目黒店,TK
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2,本郷店,TK
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2,栃木店,TO
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2,伊勢崎店,GU
...,...,...,...,...,...,...,...,...,...,...,...,...
696004,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2,足立店,TK
696005,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2,池尻店,TK
696006,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2,新宿店,TK
696007,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2,新座店,SA
696008,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2,八千代店,CH

In [20]:
# エリアマスタを結合する
order_data = pd.merge(order_data, m_area, on='area_cd', how='left')
order_data

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd,wide_area,narrow_area
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1,浅草店,TK,東京,東京
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2,目黒店,TK,東京,東京
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2,本郷店,TK,東京,東京
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2,栃木店,TO,北関東,栃木
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2,伊勢崎店,GU,北関東,群馬
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696004,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2,足立店,TK,東京,東京
696005,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2,池尻店,TK,東京,東京
696006,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2,新宿店,TK,東京,東京
696007,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2,新座店,SA,埼玉,埼玉
696008,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2,八千代店,CH,千葉,千葉

## ノック8: マスタが存在しないコードに名称設定

In [21]:
# takeout_flagの名称を設定
order_data.loc[order_data['takeout_flag']==0, 'takeout_name'] = 'デリバリー'
order_data.loc[order_data['takeout_flag']==1, 'takeout_name'] = 'お持ち帰り'
order_data

C:\Users\nao23\AppData\Local\Temp\ipykernel_13816\1816101753.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'デリバリー' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  order_data.loc[order_data['takeout_flag']==0, 'takeout_name'] = 'デリバリー'

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd,wide_area,narrow_area,takeout_name
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1,浅草店,TK,東京,東京,お持ち帰り
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2,目黒店,TK,東京,東京,デリバリー
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2,本郷店,TK,東京,東京,デリバリー
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2,栃木店,TO,北関東,栃木,デリバリー
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2,伊勢崎店,GU,北関東,群馬,デリバリー
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696004,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2,足立店,TK,東京,東京,デリバリー
696005,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2,池尻店,TK,東京,東京,デリバリー
696006,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2,新宿店,TK,東京,東京,デリバリー
696007,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2,新座店,SA,埼玉,埼玉,デリバリー
696008,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2,八千代店,CH,千葉,千葉,デリバリー

In [22]:
# statusの名称を設定
order_data.loc[order_data['status']==0, 'status_name'] = '受付'
order_data.loc[order_data['status']==1, 'status_name'] = 'お支払済'
order_data.loc[order_data['status']==2, 'status_name'] = 'お渡し済'
order_data.loc[order_data['status']==9, 'status_name'] = 'キャンセル'
order_data

C:\Users\nao23\AppData\Local\Temp\ipykernel_13816\2959486960.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '受付' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  order_data.loc[order_data['status']==0, 'status_name'] = '受付'

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd,wide_area,narrow_area,takeout_name,status_name
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1,浅草店,TK,東京,東京,お持ち帰り,お支払済
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2,目黒店,TK,東京,東京,デリバリー,お渡し済
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2,本郷店,TK,東京,東京,デリバリー,お渡し済
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2,栃木店,TO,北関東,栃木,デリバリー,お渡し済
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2,伊勢崎店,GU,北関東,群馬,デリバリー,お渡し済
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696004,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2,足立店,TK,東京,東京,デリバリー,お渡し済
696005,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2,池尻店,TK,東京,東京,デリバリー,お渡し済
696006,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2,新宿店,TK,東京,東京,デリバリー,お渡し済
696007,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2,新座店,SA,埼玉,埼玉,デリバリー,お渡し済
696008,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2,八千代店,CH,千葉,千葉,デリバリー,お渡し済

## ノック9: 分析基礎テーブルを出力

In [23]:
# csvファイルとして出力用のファイルを作成して保存
import os
output_dir = os.path.join(current_dir, 'output_data')
os.makedirs(output_dir, exist_ok=True)

output_file = os.path.join(output_dir, 'order_data.csv')
order_data.to_csv(output_file, index=False)

## ノック10: セルを整理して使いやすく

In [24]:
# ライブラリのインポート
import pandas as pd
import os
import glob

# ファイルの読込
m_store = pd.read_csv('m_store.csv')
m_area = pd.read_csv('m_area.csv')

# オーダーデータの読込
current_dir = os.getcwd()
tbl_order_file = os.path.join(current_dir, 'tbl_order_*.csv')
tbl_order_files = glob.glob(tbl_order_file)
order_all = pd.DataFrame()

for file in tbl_order_files:
    order_data = pd.read_csv(file)
    print(f'{file}:{len(order_data)}')
    order_all = pd.concat([order_all, order_data], ignore_index=True)

# 不要なデータを除外
order_data = order_all.loc[order_all['store_id'] != 999]

# マスタデータの結合
order_data = pd.merge(order_data, m_store, on='store_id', how='left')
order_data = pd.merge(order_data, m_area, on='area_cd', how='left')

# 名称を設定（お渡し方法）
order_data.loc[order_data['takeout_flag'] == 0, 'takeout_name'] = 'デリバリー'
order_data.loc[order_data['takeout_flag'] == 1, 'takeout_name'] = 'お持ち帰り'

# 名称を設定（注文状態）
order_data.loc[order_data['status'] == 0, 'status_name'] = '受付'
order_data.loc[order_data['status'] == 1, 'status_name'] = 'お支払済'
order_data.loc[order_data['status'] == 2, 'status_name'] = 'お渡し済'
order_data.loc[order_data['status'] == 9, 'status_name'] = 'キャンセル'

# ファイルの出力
output_dir = os.path.join(current_dir, 'output_data')
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, 'order_data.csv')
order_data.to_csv(output_file, index=False)

c:\Users\nao23\Documents\Python_Projects\02_MLSys_100Knocks\book\本章\1章\tbl_order_202004.csv:233260
c:\Users\nao23\Documents\Python_Projects\02_MLSys_100Knocks\book\本章\1章\tbl_order_202005.csv:241139
c:\Users\nao23\Documents\Python_Projects\02_MLSys_100Knocks\book\本章\1章\tbl_order_202006.csv:233301

C:\Users\nao23\AppData\Local\Temp\ipykernel_13816\1373023449.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'デリバリー' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  order_data.loc[order_data['takeout_flag'] == 0, 'takeout_name'] = 'デリバリー'
C:\Users\nao23\AppData\Local\Temp\ipykernel_13816\1373023449.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '受付' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  order_data.loc[order_data['status'] == 0, 'status_name'] = '受付'